apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: app
  RABBITMQ_DEFAULT_PASS: app_password_change_me
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: as5ch6ex1.azurecr.io/rabbitmq:3.12.4-management
          ports:
            - name: amqp
              containerPort: 5672
            - name: http
              containerPort: 15672
          envFrom:
            - secretRef:
                name: rabbit-secret
          # Health checks
          readinessProbe:
            exec:
              command: ["sh", "-c", "rabbitmq-diagnostics -q ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command: ["sh", "-c", "rabbitmq-diagnostics -q ping"]
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  type: ClusterIP
  selector:
    app: rabbit
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
